// The wording of plugins.nginxui.com. Capabilities and permissions use the
// words of Nginx UI, so the site and the marketplace describe them the same way.

export const LOCALES = ['en', 'zh_CN', 'zh_TW', 'ja_JP']
export const LANG = { en: 'en', zh_CN: 'zh-CN', zh_TW: 'zh-TW', ja_JP: 'ja' }
export const LANGUAGE_NAME = { en: 'English', zh_CN: '简体中文', zh_TW: '繁體中文', ja_JP: '日本語' }

export const STRINGS = {
  en: {
    title: 'Nginx UI Plugins',
    lead: 'Plugins that extend Nginx UI. To install one, open Plugins in Nginx UI and choose Marketplace.',
    search: 'Search plugins',
    empty: 'No plugin matches the search.',
    by: author => `By ${author}`,
    version: 'Version',
    beta: 'Beta',
    requires: version => `Nginx UI ${version} or later`,
    requiresLabel: 'Requires',
    platforms: 'Platforms',
    allPlatforms: 'All platforms',
    memory: 'Recommended memory',
    memoryShort: 'Memory',
    providers: count => `${count} DNS providers`,
    searchProviders: 'Search providers',
    repository: 'Repository',
    homepage: 'Homepage',
    releaseNotes: 'Release notes',
    trust: { official: 'Official', verified: 'Verified', community: 'Community' },
    submit: 'Submit a plugin',
    guide: 'Developer guide',
    catalog: 'Catalog',
    updated: 'Updated',
    language: 'Language',
    darkMode: 'Dark mode',
    allPlugins: 'All plugins',
    close: 'Close',
    previous: 'Previous',
    next: 'Next',
    about: 'About',
    screenshots: 'Screenshots',
    provides: 'Provides',
    permissions: 'Requested permissions',
    noPermissions: 'This plugin needs no access beyond its own features.',
    onlyHosts: 'Only these addresses',
    noHosts: 'No specific addresses listed',
    conflicts: names => `Cannot be enabled together with ${names.join(', ')}`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'Versions',
    latest: 'Latest',
    information: 'Information',
    id: 'ID',
    author: 'Author',
    license: 'License',
  },
  zh_CN: {
    title: 'Nginx UI 插件',
    lead: '为 Nginx UI 扩展功能的插件。安装时，在 Nginx UI 中打开“插件”并选择“市场”。',
    search: '搜索插件',
    empty: '没有符合搜索条件的插件。',
    by: author => `作者：${author}`,
    version: '版本',
    beta: '测试版',
    requires: version => `Nginx UI ${version} 或更高版本`,
    requiresLabel: '要求',
    platforms: '平台',
    allPlatforms: '所有平台',
    memory: '建议内存',
    memoryShort: '内存',
    providers: count => `${count} 个 DNS 服务商`,
    searchProviders: '搜索服务商',
    repository: '代码仓库',
    homepage: '主页',
    releaseNotes: '更新日志',
    trust: { official: '官方', verified: '已验证', community: '社区' },
    submit: '提交插件',
    guide: '开发文档',
    catalog: '插件目录',
    updated: '更新于',
    language: '语言',
    darkMode: '深色模式',
    allPlugins: '全部插件',
    close: '关闭',
    previous: '上一张',
    next: '下一张',
    about: '简介',
    screenshots: '截图',
    provides: '提供',
    permissions: '请求的权限',
    noPermissions: '此插件除自身功能外不需要其他访问权限。',
    onlyHosts: '仅限以下地址',
    noHosts: '未列出具体地址',
    conflicts: names => `不能与${names.map(name => `“${name}”`).join('、')}同时启用`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: '版本',
    latest: '最新',
    information: '信息',
    id: 'ID',
    author: '作者',
    license: '开源许可',
  },
  zh_TW: {
    title: 'Nginx UI 外掛',
    lead: '為 Nginx UI 擴充功能的外掛。安裝時，在 Nginx UI 中開啟「外掛」並選擇「市集」。',
    search: '搜尋外掛',
    empty: '沒有符合搜尋條件的外掛。',
    by: author => `作者：${author}`,
    version: '版本',
    beta: '測試版',
    requires: version => `Nginx UI ${version} 或更新版本`,
    requiresLabel: '需求',
    platforms: '平台',
    allPlatforms: '所有平台',
    memory: '建議記憶體',
    memoryShort: '記憶體',
    providers: count => `${count} 個 DNS 服務商`,
    searchProviders: '搜尋服務商',
    repository: '原始碼庫',
    homepage: '首頁',
    releaseNotes: '發行說明',
    trust: { official: '官方', verified: '已驗證', community: '社群' },
    submit: '提交外掛',
    guide: '開發文件',
    catalog: '外掛目錄',
    updated: '更新於',
    language: '語言',
    darkMode: '深色模式',
    allPlugins: '全部外掛',
    close: '關閉',
    previous: '上一張',
    next: '下一張',
    about: '簡介',
    screenshots: '螢幕截圖',
    provides: '提供',
    permissions: '要求的權限',
    noPermissions: '此外掛除自身功能外不需要其他存取權限。',
    onlyHosts: '僅限以下位址',
    noHosts: '未列出具體位址',
    conflicts: names => `不能與${names.map(name => `「${name}」`).join('、')}同時啟用`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: '版本',
    latest: '最新',
    information: '資訊',
    id: 'ID',
    author: '作者',
    license: '開源授權',
  },
  ja_JP: {
    title: 'Nginx UI プラグイン',
    lead: 'Nginx UI の機能を広げるプラグインです。インストールするには、Nginx UI で「プラグイン」を開き、「マーケットプレイス」を選びます。',
    search: 'プラグインを検索',
    empty: '検索に一致するプラグインはありません。',
    by: author => `著者：${author}`,
    version: 'バージョン',
    beta: 'ベータ版',
    requires: version => `Nginx UI ${version} 以降`,
    requiresLabel: '必要条件',
    platforms: 'プラットフォーム',
    allPlatforms: 'すべてのプラットフォーム',
    memory: '推奨メモリ',
    memoryShort: 'メモリ',
    providers: count => `DNS プロバイダー ${count} 件`,
    searchProviders: 'プロバイダーを検索',
    repository: 'リポジトリ',
    homepage: 'ホームページ',
    releaseNotes: 'リリースノート',
    trust: { official: '公式', verified: '検証済み', community: 'コミュニティ' },
    submit: 'プラグインを提出',
    guide: '開発者ガイド',
    catalog: 'カタログ',
    updated: '更新日',
    language: '言語',
    darkMode: 'ダークモード',
    allPlugins: 'すべてのプラグイン',
    close: '閉じる',
    previous: '前へ',
    next: '次へ',
    about: '概要',
    screenshots: 'スクリーンショット',
    provides: '提供する機能',
    permissions: '要求される権限',
    noPermissions: 'このプラグインは自身の機能以外へのアクセスを必要としません。',
    onlyHosts: 'これらのアドレスのみ',
    noHosts: '特定のアドレスは指定されていません',
    conflicts: names => `${names.map(name => `「${name}」`).join('、')}と同時に有効にできません`,
    minVersion: version => `Nginx UI ${version}+`,
    versions: 'バージョン',
    latest: '最新',
    information: '情報',
    id: 'ID',
    author: '著者',
    license: 'ライセンス',
  },
}

export const CAPABILITIES = {
  'dns01': {
    label: { en: 'Certificate DNS validation', zh_CN: '证书 DNS 验证', zh_TW: '憑證 DNS 驗證', ja_JP: '証明書の DNS 検証' },
    description: { en: 'Validates domains through DNS records when certificates are issued or renewed.', zh_CN: '在签发或续期证书时通过 DNS 记录验证域名。', zh_TW: '在簽發或續期憑證時透過 DNS 記錄驗證網域。', ja_JP: '証明書の発行または更新時に DNS レコードでドメインを検証します。' },
  },
  'http': {
    label: { en: 'Web pages and API', zh_CN: '网页与 API', zh_TW: '網頁與 API', ja_JP: 'Web ページと API' },
    description: { en: 'Serves its own pages and API inside Nginx UI.', zh_CN: '在 Nginx UI 中提供自己的页面和 API。', zh_TW: '在 Nginx UI 中提供自己的頁面和 API。', ja_JP: 'Nginx UI 内で独自のページと API を提供します。' },
  },
  'notify': {
    label: { en: 'External notifications', zh_CN: '外部通知', zh_TW: '外部通知', ja_JP: '外部通知' },
    description: { en: 'Delivers Nginx UI notifications to other services.', zh_CN: '将 Nginx UI 的通知发送到其他服务。', zh_TW: '將 Nginx UI 的通知傳送至其他服務。', ja_JP: 'Nginx UI の通知を他のサービスに配信します。' },
  },
  'probe': {
    label: { en: 'Health checks', zh_CN: '健康检查', zh_TW: '健康檢查', ja_JP: 'ヘルスチェック' },
    description: { en: 'Adds more ways to check whether sites and services are reachable.', zh_CN: '增加更多检查站点和服务是否可达的方式。', zh_TW: '增加更多檢查網站和服務是否可連線的方式。', ja_JP: 'サイトやサービスに到達できるかを確認する方法を追加します。' },
  },
  'mcp': {
    label: { en: 'AI assistant tools', zh_CN: 'AI 助手工具', zh_TW: 'AI 助理工具', ja_JP: 'AI アシスタントツール' },
    description: { en: 'Offers actions that AI assistants connected to Nginx UI can run.', zh_CN: '提供可供连接到 Nginx UI 的 AI 助手执行的操作。', zh_TW: '提供可供連接到 Nginx UI 的 AI 助理執行的操作。', ja_JP: 'Nginx UI に接続された AI アシスタントが実行できる操作を提供します。' },
  },
  'storage': {
    label: { en: 'Backup storage', zh_CN: '备份存储', zh_TW: '備份儲存', ja_JP: 'バックアップストレージ' },
    description: { en: 'Stores backups and other files in external storage.', zh_CN: '将备份和其他文件保存到外部存储。', zh_TW: '將備份和其他檔案儲存到外部儲存空間。', ja_JP: 'バックアップやその他のファイルを外部ストレージに保存します。' },
  },
  'cert.deploy': {
    label: { en: 'Certificate deployment', zh_CN: '证书部署', zh_TW: '憑證部署', ja_JP: '証明書のデプロイ' },
    description: { en: 'Pushes issued certificates to other services and devices.', zh_CN: '将签发的证书推送到其他服务和设备。', zh_TW: '將簽發的憑證推送至其他服務和裝置。', ja_JP: '発行された証明書を他のサービスやデバイスへプッシュします。' },
  },
  'security.blocklist': {
    label: { en: 'Blocklists', zh_CN: '封锁列表', zh_TW: '封鎖清單', ja_JP: 'ブロックリスト' },
    description: { en: 'Keeps lists of addresses that are denied access up to date.', zh_CN: '持续更新禁止访问的地址列表。', zh_TW: '持續更新禁止存取的位址清單。', ja_JP: 'アクセスを拒否するアドレスのリストを最新に保ちます。' },
  },
  'upstream.discovery': {
    label: { en: 'Service discovery', zh_CN: '服务发现', zh_TW: '服務探索', ja_JP: 'サービスディスカバリー' },
    description: { en: 'Finds backend servers automatically and keeps upstreams up to date.', zh_CN: '自动发现后端服务器，并保持 upstream 为最新状态。', zh_TW: '自動探索後端伺服器，並保持 upstream 為最新狀態。', ja_JP: 'バックエンドサーバーを自動的に検出し、upstream を最新に保ちます。' },
  },
  'log.sink': {
    label: { en: 'Access log forwarding', zh_CN: '访问日志转发', zh_TW: '存取日誌轉發', ja_JP: 'アクセスログの転送' },
    description: { en: 'Receives access log entries as they are written, for example to forward or analyse them.', zh_CN: '在访问日志写入时实时接收日志条目，例如用于转发或分析。', zh_TW: '在存取日誌寫入時即時接收日誌項目，例如用於轉發或分析。', ja_JP: 'アクセスログのエントリを書き込み時に受け取ります。転送や分析などに使用します。' },
  },
}

export const OTHER_CAPABILITY = {
  label: { en: 'Other feature', zh_CN: '其他功能', zh_TW: '其他功能', ja_JP: 'その他の機能' },
  description: { en: 'A feature this version of Nginx UI does not describe.', zh_CN: '此版本的 Nginx UI 未描述的功能。', zh_TW: '此版本的 Nginx UI 未描述的功能。', ja_JP: 'このバージョンの Nginx UI では説明されていない機能です。' },
}

export const PERMISSIONS = {
  'kv': {
    label: { en: 'Own data storage', zh_CN: '自有数据存储', zh_TW: '自有資料儲存', ja_JP: '独自のデータストレージ' },
    description: { en: 'Keep its own data inside Nginx UI.', zh_CN: '在 Nginx UI 中保存自己的数据。', zh_TW: '在 Nginx UI 中儲存自己的資料。', ja_JP: '独自のデータを Nginx UI 内に保存します。' },
  },
  'network': {
    label: { en: 'Network', zh_CN: '网络', zh_TW: '網路', ja_JP: 'ネットワーク' },
    description: { en: 'Connect to other servers over the network.', zh_CN: '通过网络连接到其他服务器。', zh_TW: '透過網路連線到其他伺服器。', ja_JP: 'ネットワーク経由で他のサーバーに接続します。' },
  },
  'cron': {
    label: { en: 'Scheduled tasks', zh_CN: '计划任务', zh_TW: '排程任務', ja_JP: 'スケジュールタスク' },
    description: { en: 'Run tasks on a regular schedule.', zh_CN: '按固定计划执行任务。', zh_TW: '依固定排程執行任務。', ja_JP: '定期的なスケジュールでタスクを実行します。' },
  },
  'notify': {
    label: { en: 'Notifications', zh_CN: '通知', zh_TW: '通知', ja_JP: '通知' },
    description: { en: 'Send notifications through the Nginx UI notification channels.', zh_CN: '通过 Nginx UI 的通知渠道发送通知。', zh_TW: '透過 Nginx UI 的通知管道發送通知。', ja_JP: 'Nginx UI の通知チャネルを通じて通知を送信します。' },
  },
  'metrics.read': {
    label: { en: 'Server metrics', zh_CN: '服务器指标', zh_TW: '伺服器指標', ja_JP: 'サーバーメトリクス' },
    description: { en: 'Read CPU, memory, network and Nginx status metrics of this node.', zh_CN: '读取本节点的 CPU、内存、网络及 Nginx 状态指标。', zh_TW: '讀取此節點的 CPU、記憶體、網路及 Nginx 狀態指標。', ja_JP: 'このノードの CPU、メモリ、ネットワーク、Nginx のステータス指標を読み取ります。' },
  },
  'core_api': {
    label: { en: 'Nginx UI management', zh_CN: 'Nginx UI 管理', zh_TW: 'Nginx UI 管理', ja_JP: 'Nginx UI の管理' },
    description: { en: 'Manage Nginx UI with your permissions.', zh_CN: '以您的权限管理 Nginx UI。', zh_TW: '以您的權限管理 Nginx UI。', ja_JP: 'あなたの権限で Nginx UI を管理します。' },
  },
  'mcp': {
    label: { en: 'AI assistant tools', zh_CN: 'AI 助手工具', zh_TW: 'AI 助理工具', ja_JP: 'AI アシスタントツール' },
    description: { en: 'Offer actions that AI assistants connected to Nginx UI can run.', zh_CN: '提供可供连接到 Nginx UI 的 AI 助手执行的操作。', zh_TW: '提供可供連接到 Nginx UI 的 AI 助理執行的操作。', ja_JP: 'Nginx UI に接続された AI アシスタントが実行できる操作を提供します。' },
  },
  'cert.deploy': {
    label: { en: 'Certificates', zh_CN: '证书', zh_TW: '憑證', ja_JP: '証明書' },
    description: { en: 'Receive issued certificates, including the parts that must stay secret, to push them to other services.', zh_CN: '接收签发的证书（包括必须保密的部分），以推送到其他服务。', zh_TW: '接收簽發的憑證（包括必須保密的部分），以推送至其他服務。', ja_JP: '発行された証明書を、秘密にすべき部分も含めて受け取り、他のサービスへプッシュします。' },
  },
  'log.read': {
    label: { en: 'Access logs', zh_CN: '访问日志', zh_TW: '存取日誌', ja_JP: 'アクセスログ' },
    description: { en: 'Receive every access log entry while it is on, including visitor addresses and requested URLs.', zh_CN: '开启期间接收每条访问日志，包括访客地址和请求的 URL。', zh_TW: '開啟期間接收每筆存取日誌，包括訪客位址和請求的 URL。', ja_JP: 'オンの間、訪問者のアドレスやリクエストされた URL を含むすべてのアクセスログを受け取ります。' },
  },
  'log.files': {
    label: { en: 'Log files', zh_CN: '日志文件', zh_TW: '日誌檔案', ja_JP: 'ログファイル' },
    description: { en: 'Read the Nginx log files of this node, including visitor addresses and requested URLs.', zh_CN: '读取此节点的 Nginx 日志文件，其中包含访客地址和请求的 URL。', zh_TW: '讀取此節點的 Nginx 日誌檔案，其中包含訪客位址和請求的 URL。', ja_JP: 'このノードの Nginx ログファイルを読み取ります。訪問者のアドレスやリクエストされた URL が含まれます。' },
  },
  'nginx.snippet': {
    label: { en: 'Nginx configuration snippets', zh_CN: 'Nginx 配置片段', zh_TW: 'Nginx 設定片段', ja_JP: 'Nginx 設定スニペット' },
    description: { en: 'Add Nginx configuration of its own. It takes effect only where you include it, and Nginx UI applies it only when the configuration remains valid.', zh_CN: '添加它自己的 Nginx 配置。配置只在你引入它的位置生效，且只有在整体配置仍然有效时，Nginx UI 才会应用它。', zh_TW: '新增它自己的 Nginx 設定。設定只在你引入它的位置生效，且只有在整體設定仍然有效時，Nginx UI 才會套用它。', ja_JP: '独自の Nginx 設定を追加します。設定は読み込んだ場所でのみ有効になり、Nginx UI は設定全体が有効な場合にのみ適用します。' },
  },
  'nginx.config.read': {
    label: { en: 'Nginx configuration', zh_CN: 'Nginx 配置', zh_TW: 'Nginx 設定', ja_JP: 'Nginx 設定' },
    description: { en: 'Read the Nginx configuration files of this node.', zh_CN: '读取此节点的 Nginx 配置文件。', zh_TW: '讀取此節點的 Nginx 設定檔。', ja_JP: 'このノードの Nginx 設定ファイルを読み取ります。' },
  },
  'sites.read': {
    label: { en: 'Sites', zh_CN: '站点', zh_TW: '站點', ja_JP: 'サイト' },
    description: { en: 'See the sites of this node and their addresses.', zh_CN: '查看此节点的站点及其地址。', zh_TW: '檢視此節點的站點及其位址。', ja_JP: 'このノードのサイトとそのアドレスを表示します。' },
  },
  'certs.read': {
    label: { en: 'Certificate list', zh_CN: '证书列表', zh_TW: '憑證清單', ja_JP: '証明書一覧' },
    description: { en: 'See the certificates and when they expire, without the parts that must stay secret.', zh_CN: '查看证书及其到期时间，不包括必须保密的部分。', zh_TW: '檢視憑證及其到期時間，不包括必須保密的部分。', ja_JP: '秘密にすべき部分を除き、証明書とその有効期限を表示します。' },
  },
}

/** credentials.read:<kind>, the kind filled in. */
export const CREDENTIALS_PERMISSION = {
  label: { en: kind => `Stored ${kind} credentials`, zh_CN: kind => `已保存的 ${kind} 凭证`, zh_TW: kind => `已儲存的 ${kind} 憑證`, ja_JP: kind => `保存されている ${kind} の資格情報` },
  description: { en: kind => `Read stored ${kind} credentials, including their secrets.`, zh_CN: kind => `读取已保存的 ${kind} 凭据，包括其密钥。`, zh_TW: kind => `讀取已儲存的 ${kind} 憑證，包括其密鑰。`, ja_JP: kind => `保存されている ${kind} の資格情報を、シークレットを含めて読み取ります。` },
}

export const UNKNOWN_PERMISSION = {
  label: { en: 'Unknown permission', zh_CN: '未知权限', zh_TW: '未知權限', ja_JP: '不明な権限' },
  description: { en: 'Unknown permission. Only grant it if you trust the plugin author.', zh_CN: '未知权限，请仅在信任插件作者时授予。', zh_TW: '未知權限，請僅在信任外掛作者時授予。', ja_JP: '不明な権限です。プラグインの作者を信頼できる場合のみ許可してください。' },
}
